### ISSUE TITLE
Fix settings file link

### ISSUE THREAD

**Issue by Sahaj-IBM** [ibm-client-engineering/solution-wxai-aws#112]
When you click on the settings file it doesn't open to the file

![Screenshot 2024-05-31 at 9 50 19 AM](https://github.com/ibm-client-engineering/solution-wxai-aws/assets/139918147/d12626ba-2610-46a8-b002-3eae225e596a)

**Comment by shirley336** [comment]
Fixed settings link code pushed. Also, in this PR: https://github.com/ibm-client-engineering/solution-wxai-aws/pull/114
